  - debug: var=ssmtp_user
  - debug: var=ssmtp_password

  - name: instal packages
    apt:
      update_cache: true 
      state: present
      pkg:
        - avahi-daemon
        - ssmtp 
        - logwatch 
        - libacl1 
        - build-essential 
        - fuse 
        - pkg-config 
        - unattended-upgrades 
        - apt-listchanges 
        - ethtool          
        - iptables 
        - systemd-timesyncd
        - jq
        - ipmitool
       

  - name: ssmtp configuration
    template:
      src: templates/ssmtp.conf.j2
      dest: /etc/ssmtp/ssmtp.conf
      backup: true

  - name: ssmtp revaliases
    template:
      src: templates/revaliases.j2
      dest: /etc/ssmtp/revaliases
      backup: yes

  - name: ssh.servics
    copy:
      src: files/ssh.service
      dest: /etc/avahi/services/ssh.service
      backup: true

  - name: sftp.service
    copy:
      src: files/sftp.service
      dest:  /etc/avahi/services/sftp.service
      backup: true

  - name: services avahi-daemon
    systemd:
      name: avahi-daemon.service
      state: started
      enabled: yes

  - name: auto-upgrades
    copy:
      src: files/20auto-upgrades
      dest: /etc/apt/apt.conf.d/20auto-upgrades
      backup: true

  - name: services unattended-upgrades
    systemd: 
      name: unattended-upgrades.service
      state: started
      enabled: yes

  - name: add contrib repository
    replace:
      dest: /etc/apt/sources.list
      regexp: '^(deb(?!.* contrib).*)'

  - name: Add non-free-firmware repository
    replace:
      dest: /etc/apt/sources.list      
      regexp: '^(deb(?!.* non-free-firmware).*)'
      replace: '\1 non-free-firmware'
    when: ansible_distribution == 'Debian' and ansible_lsb.major_release|int >= 12

  - name: Add non-free repository
    replace:
      dest: /etc/apt/sources.list
      regexp: '^(deb(?!.* non-free).*)'
      replace: '\1 non-free'