  # code=ansible

  - name: Instal packages
    apt: 
        pkg={{item}} 
        state=present 
        install_recommends=true
    with_items:
    - libvirt-daemon-system
    - qemu-kvm
    - bridge-utils
    - libvirt-clients
    - virt-manager
    update_cache: true            

  - name: adding existing user '{{ lookup('env','USER') }}' to group libvirt
    user:
      name: "{{ lookup('env','USER') }}"
      groups: libvirt
      append: yes

  - name: adding existing user '{{ lookup('env','USER') }}' to group libvirt-qemu
    user:
      name: "{{ lookup('env','USER') }}"
      groups: libvirt-qemu
      append: yes

  - name: sysctl netfilter
    copy:
      src: files/99-netfilter-bridge.conf
      dest: /etc/sysctl.d/99-netfilter-bridge.conf
      backup: true

  - name: modules netfilter
    copy:
      src: files/br_netfilter.conf
      dest: /etc/modules-load.d/br_netfilter.conf
      backup: true

  - name: aliases
    copy:
      src: files/virsh
      dest: /etc/profile.d/virsh
      backup: true
