- hosts: all
  become: yes
  remote_user: ansible

  pre_tasks:
  - name: update APT cache
    apt: update_cache=yes cache_valid_time=28800
    when: ansible_os_family == 'Debian'

  vars:
    ipv6net: "2a06:4004:90f2:4567::/80"

  roles:
    - docker
