  - name: add sshkey to user root
    authorized_key:
      user: root
      state: present
      manage_dir: true
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

  - name: create user ansible
    user:
      name: ansible
      state: present        
      shell: /bin/bash
      groups: sudo
      append: yes

  - name: add sudo rights for ansible
    copy:
      dest: /etc/sudoers.d/ansible      
      content: "ansible ALL=(root) NOPASSWD: ALL"
      backup: true
      mode: 0644

  - name: add sshkey to user ansible
    authorized_key:
      user: ansible
      state: present
      manage_dir: true
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

  - name: add non-free-firmware to /etc/apt/sources.list
    replace:
      path: /etc/apt/sources.list      
      regexp: '\s*(deb.+)(?<! non-free-firmware)$'
      replace: '\1 non-free-firmware\n'
      backup: true

  - name: is pve-enterprise
    stat:
      path: /etc/apt/sources.list.d/pve-enterprise.list
    register: pve_enterprise

  - name: disable pve-enterprise repo
    replace:
      path: /etc/apt/sources.list.d/pve-enterprise.list
      regexp: '^\s*(deb.*)' 
      replace: '# \1\n'      
      backup: true
    when: pve_enterprise.stat.exists

  - name: is ceph
    stat:
      path: /etc/apt/sources.list.d/ceph.list
    register: ceph

  - name: disable ceph repo
    replace:
      path: /etc/apt/sources.list.d/ceph.list
      regexp: '^\s*(deb.*)' 
      replace: '# \1\n'      
      backup: true
    when: ceph.stat.exists

  - name: add community repo
    apt_repository:
      repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
      filename: pve-community
      state: present
    notify: update apt cache

  - name: install packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - intel-microcode
      - vim

  - name: disable proxmox subscription nagging
    replace:
      path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
      regexp: '^(.*)Ext\.Msg\.show\(\{(.*)$\n^(.*)No valid subscription(.*)$'
      replace: '\1void({\2\n\3No valid subscription\4'
      backup: true
    notify: restart pveproxy