- name: install
  apt:
    state: present
    pkg:
      - lxc
      - libvirt0
      - libpam-cgfs
      - bridge-utils 
      - uidmap
    update_cache: true        
    
- name: default.conf
  copy:
    src: files/default.conf
    dest: /etc/lxc/default.conf
    backup: yes    
      
- name: lxc-net
  copy:
    src: files/lxc-net
    dest: /etc/default/lxc-net
    backup: yes

