
  - name: Instal packages
    apt:
      state: present
      install_recommends: false
      pkg:
        - bridge-utils

  - name: get docker
    get_url: 
      url: https://get.docker.com 
      dest: /tmp/get-docker.sh 
      mode: 755

  - name: install docker
    shell:
      cmd: |
        apt update
        sh /tmp/get-docker.sh

  - name: install composer plugin
    apt:
      name: docker-compose-plugin
      state: present
    
  - name: update docker.json
    template:
      src: templates/daemon.json.j2
      dest: /etc/docker/daemon.json
      backup: true

  - name: install docker-compose (legacy)
    get_url: 
      url: https://raw.githubusercontent.com/linuxserver/docker-docker-compose/master/run.sh
      dest: /usr/local/bin/docker-compose
      mode: 755

  - name: restart docker
    systemd:
      name: docker.service
      state: reloaded      
      enabled: yes
      masked: no

  - name: create docker user
    user:
      name: docker
      state: present      
      shell: /bin/bash
      groups: sudo
      append: yes

  - name: add sshkey to docker user 
    authorized_key:
      user: docker
      state: present
      manage_dir: true
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
      
  - name: adding docker user to group docker
    user:
      name: docker
      groups: docker
      append: yes
  